### ISSUE TITLE
Check docker image that reana training is based on

### ISSUE THREAD

**Issue by klieret** [hsf-training/hsf-training-reana-webpage#8]

**Comment by tiborsimko** [comment]
Tested all the lesson recipes using the "snapshotted" docker image, as well as using a docker images produced by the latest [HSF lesson on Docker](https://hsf-training.github.io/hsf-training-docker/), and everything is working well.

The porting of examples to run on latest REANA 0.9.1 was recently merged, so we can close this isuse.
